Add CSP and CSPEE patches
WICG/fenced-frame pull request #72
Opened 2023-04-12 17:14 UTC by blu25

2023-04-12 19:30 UTC, domfarolino commented on spec.bs
> +<h3 id=csp-integration>CSP Integration</h3>
I think this section might be best to appear under the "Interactions with other specifications" section instead of the "HTML Integration" section.

2023-04-12 19:30 UTC, domfarolino commented on spec.bs
> +created in secure contexts and require the embedder to give permissions to all sources (i.e.
Link to secure context dfn

2023-04-12 19:30 UTC, domfarolino commented on spec.bs
> +"`https:`", "`https://*:*`", or "`*`"). This is done to prevent using [[!CSP]] for cross-channel
side-channel, not cross-channel

2023-04-12 19:30 UTC, domfarolino commented on spec.bs
> +Add a step after step 2 of the [=frame-src pre-request check=] that says:
Put all of these in algorithm blocks so the variables don't leak out.

2023-04-17 12:14 UTC, domfarolino commented
Closing and re-opening to maybe get PR preview to work again...

2023-04-21 23:56 UTC, domfarolino requested changes

2023-04-21 23:56 UTC, domfarolino commented on spec.bs
> +  Add a step after step 2 of the [=frame-src pre-request check=] that says:
I get the impression that these algorithms are wrong. Why do we apply these checks only in the `frame-src` directive? What if there is no `frame-src` or `fenced-frame-src` directive supplied in a page's policy, but there is a `default-src` that provides a specific origin? In that case, it seems like the `default-src` directive would execute by the normal rules, instead of our special FF-only rules, thus introducing the communication channel that we're trying to avoid, right? Same goes for if `child-src` is supplied, but not `frame-src` or `fenced-frame-src`.

Let me know if you also think this is a problem, and if so maybe to fix this we need to amend *every* pre-request directive check in the `fenced-frame-src` fallback directive list to abide by the FF-specific rules in the event the request's destination is `fencedframe`. That's a pretty easy change but I want to see if you think I'm on the right path or missing something.

2023-04-21 23:56 UTC, domfarolino commented on spec.bs
> +  Add a step after step 2 of the [=frame-src pre-request check=] that says:
I agree with doing this after step 2 instead of after step 3. But one thing I want to double check is that _only_ handling the case where the supplied directive's policy _does not_ contain the allowed values is OK. For example what if the supplied policy _does_ contain an allowed policy like `https:` but also contains `'none'` (i.e., `Content-Security-Policy: fenced-frame-src https: 'none'`). Your modifications to the `frame-src` directive will result in CSP spec invoking https://w3c.github.io/webappsec-csp/#match-url-to-source-list, which seems to iterate over each source expression, and _if any_ of the match, we return "Matches". So I think there's no issue here, but I just want to double check that my reading matches yours.

2023-04-21 23:56 UTC, domfarolino commented on spec.bs
> +Fenced frames are a different element from an iframe. Therefore, using the
Somewhere in this section we'll need to modify https://w3c.github.io/webappsec-csp/#effective-directive-for-a-request right?

2023-04-23 14:09 UTC, domfarolino commented on spec.bs
> +  Add a step after step 2 of the [=frame-src pre-request check=] that says:
> if so maybe to fix this we need to amend every pre-request directive check in the `fenced-frame-src` fallback directive list to abide by the FF-specific rules in the event the request's destination is `fencedframe`

Upon further thought, maybe this is correct as-is, since the `child-src` and `default-src` pre-request checks both defer to _other_ directives (see their step 3) which in this case will defer to `frame-src` and `fenced-frame-src` pre-request checks which both are modified by this spec. Is that the intention?

2023-04-24 20:35 UTC, blu25 commented on spec.bs
> +  Add a step after step 2 of the [=frame-src pre-request check=] that says:
https://w3c.github.io/webappsec-csp/#directive-fallback-list I think that's right.

Yes. The intention is to have both frame-src and fenced-frame-src properly gated for fenced frames. Since we don't want people to be able to bypass restrictions we're adding simply by changing the CSP directive.

2023-04-24 20:40 UTC, blu25 commented on spec.bs
> +  Add a step after step 2 of the [=frame-src pre-request check=] that says:
Yes, that matches what I saw. Step 4.1 returns early once it finds one match, so I think this logic is sound.

2023-04-24 22:03 UTC, domfarolino commented on spec.bs
> +  Add a step after step 2 of the [=frame-src pre-request check=] that says:
I understand that I'm just making sure we're not missing anything by _not_ gating any other algorithms i.e., the more general `default-src`, `child-src`, or even the actual algorithms that do the matching. It looks like we're fine though.

2023-04-24 22:18 UTC, domfarolino approved these changes

2023-04-24 22:18 UTC, merged